name: Sync Translations
on:
  # schedule:
  #   - cron: '0 12 * * WED'  # Every Wednesday at midnight
  workflow_dispatch:
jobs:
  sync_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Pandas translations
        uses: Scientific-Python-Translations/translations-sync@main
        with:
          crowdin-project: "Pandas"
          source-repo: "pandas-dev/pandas"
          source-folder: "web/pandas/"
          source-ref: "main"
          translations-repo: "Scientific-Python-Translations/pandas-translations"
          translations-path: "web/pandas/content/"
          translations-source-path: "web/pandas/content/en/"
          translations-ref: "main"
          translation-percentage: "90"
          approval-percentage: "0"
          use-pre-commit: "false"
          create-upstream-pr: "false"
          auto-merge: "false"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
          crowdin-token: ${{ secrets.CROWDIN_TOKEN }}
