name: Sync Content

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    # Run only on main branch in upstream repo.
    if: ${{ github.repository == 'scientific-python-translations/pandas-translations' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Set the branch name with more granularity
        run: echo "BRANCH_NAME=updates-$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_ENV

      - name: Checkout pandas
        uses: actions/checkout@v4
        with:
          repository: 'pandas-dev/pandas'
          path: 'pandas'
          ref: 'main'

      - name: Checkout pandas-translations
        uses: actions/checkout@v4
        with:
          path: 'pandas-translations'
          ref: 'main'

      - name: Sync the website content
        run: |
          rsync -av --delete pandas/web/pandas/ pandas-translations/content/en/
          cd pandas-translations
          git checkout -b ${{ env.BRANCH_NAME }}
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          # Only proceed to commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit."
            echo "CONTENT_CHANGED=false" >> $GITHUB_ENV
          else
            git commit -m "Update website content"
            echo "CONTENT_CHANGED=true" >> $GITHUB_ENV
          fi
          git commit -m "Update website content" -a || echo "No changes to commit"
          git push -u origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        if: env.CONTENT_CHANGED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh pr create --base main --head ${{ env.BRANCH_NAME }} --title "Update source content" --body "Automated update of Pandas content."
        working-directory: ./pandas-translations
