name: Sync Content
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Pandas Content
        uses: Scientific-Python-Translations/content-sync@main
        with:
          source-repo: "pandas-dev/pandas"
          source-path: "web/pandas/"
          source-ref: "main"
          translations-repo: "Scientific-Python-Translations/pandas-translations"
          translations-path: "web/pandas/content/"
          translations-source-path: "web/pandas/content/en/"
          translations-ref: "main"
          auto-merge: "false"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
